/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eegsmart_imagetransfer_jni_PreviewJNI */

#ifndef _Included_com_eegsmart_imagetransfer_jni_PreviewJNI
#define _Included_com_eegsmart_imagetransfer_jni_PreviewJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eegsmart_imagetransfer_jni_PreviewJNI
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eegsmart_imagetransfer_jni_PreviewJNI_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_eegsmart_imagetransfer_jni_PreviewJNI
 * Method:    shutDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eegsmart_imagetransfer_jni_PreviewJNI_shutDown
  (JNIEnv *, jclass);

/*
 * Class:     com_eegsmart_imagetransfer_jni_PreviewJNI
 * Method:    takePicture
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eegsmart_imagetransfer_jni_PreviewJNI_takePicture
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_eegsmart_imagetransfer_jni_PreviewJNI
 * Method:    isTakingPicture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_eegsmart_imagetransfer_jni_PreviewJNI_isTakingPicture
  (JNIEnv *, jclass);

/*
 * Class:     com_eegsmart_imagetransfer_jni_PreviewJNI
 * Method:    recordStart
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eegsmart_imagetransfer_jni_PreviewJNI_recordStart
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_eegsmart_imagetransfer_jni_PreviewJNI
 * Method:    recording
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_eegsmart_imagetransfer_jni_PreviewJNI_recording
  (JNIEnv *, jclass);

/*
 * Class:     com_eegsmart_imagetransfer_jni_PreviewJNI
 * Method:    recordStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eegsmart_imagetransfer_jni_PreviewJNI_recordStop
  (JNIEnv *, jclass);

/*
 * Class:     com_eegsmart_imagetransfer_jni_PreviewJNI
 * Method:    setDecodeFrame
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_eegsmart_imagetransfer_jni_PreviewJNI_setDecodeFrame
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
