/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_es_ehuman_EHuman_OnResultListener */

#ifndef _Included_com_es_ehuman_EHuman_OnResultListener
#define _Included_com_es_ehuman_EHuman_OnResultListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
